Repository ProboCI/probo-docs, pull requests merged in 2018-09, with the labels that each got.

#95 PB-572: update config description of setting phpIniOptions on the lam…
  _recipes/lamp_set_php_config.md
  _recipes/lamp_set_php_config_on_drupal.md
  docs/plugins/lamp-plugin.md
Labels: ready to deploy

#96 PB-575: Replace plugin tables with rows.
  _plugins/details.rb
  _plugins/option.rb
  _plugins/option_list.rb
  _stylesheets/02-atoms/_all.scss
  _stylesheets/02-atoms/_option-example.scss
  _stylesheets/02-atoms/_typography.scss
  css/probo.css
  css/probo_docs.css
  docs/plugins/drupal-plugin.md
  docs/plugins/lamp-plugin.md
  docs/plugins/wordpress-plugin.md
Labels: enhancement

#98 Adding additional LAMP Plugin examples.
  docs/plugins/lamp-plugin.md
Labels: needs review

#99 Update vulnerable dependencies.
  Gemfile
  Gemfile.lock
Labels: ready to deploy
